dist: xenial   # required for Python >= 3.7
language: python
os:
  - linux
python:
  - "3.7"
sudo: false
install:
  # Python 3.x is default
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Prepare env with Python version
  - conda create -n psearch python=$TRAVIS_PYTHON_VERSION
  # Update now the env with our environment
  - conda env update -f environment.yml
  - source activate psearch
  # Install psearch
  - pip install ".[dev]"
script:
  - pytest -v -m 'not online' tests/
  - flake8
